import { Platform } from 'react-native';
import { TestIds } from 'react-native-google-mobile-ads';

// The app loads the hosted game, so every push to GitHub Pages updates the app without a store release.
// Change both lines together if the game moves to a custom domain.
export const GAME_URL = 'https://w2001-rf.github.io/skyway-3D-simulator/';
export const GUIDE_URL = GAME_URL + 'guide.html';

// AdMob interstitial unit IDs (AdMob › Apps › Ad units). Until they are filled in, and in every
// development build, Google's test units are used, so no real impressions are ever generated by mistake.
const PROD_INTERSTITIAL = Platform.select({ android: '', ios: '', default: '' });
export const INTERSTITIAL_ID = !__DEV__ && PROD_INTERSTITIAL ? PROD_INTERSTITIAL : TestIds.INTERSTITIAL;

// Frequency cap on top of the game's own (150 s of actual flying between two ad breaks)
export const AD_FIRST_DELAY_MS = 3 * 60_000;    // no ad during the first minutes of a session
export const AD_MIN_GAP_MS = 4 * 60_000;        // minimum time between two interstitials
